- name: Demo on condtions
  hosts: localhost
  vars:
    fruit : Apple , orange

  tasks:
    - name: Print Apple Price
      ansible.builtin.debug:
        msg: Apple price is 50
      vars:
      fruit: Apple
      when: fruit == "Apple"


    - name: Print Orange Price
      ansible.builtin.debug:
        msg: Orange price is 60
      vars:
      fruit: Apple
      when: fruit == "Apple"
